# Generated by Django 4.1.5 on 2023-01-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_remove_contact_employee_remove_contact_hospital_and_more"),
        ("employee", "0002_employee_contact_alter_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.contact",
            ),
        ),
    ]
