# Generated by Django 4.1.5 on 2023-01-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_remove_contact_employee_remove_contact_hospital_and_more"),
        ("pathology", "0002_remove_pathology_patient"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.contact",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="pathology",
            field=models.ManyToManyField(
                related_name="patient", to="pathology.pathology"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="password",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
