# Generated by Django 4.1.5 on 2023-01-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathology", "0002_remove_pathology_patient"),
        ("patient", "0002_patient_contact_alter_patient_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="pathology",
            field=models.ManyToManyField(
                related_name="patient", to="pathology.pathology"
            ),
        ),
    ]
