# Generated by Django 4.1.5 on 2023-01-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_pathology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="password",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
