# Generated by Django 4.1.5 on 2023-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("number", models.IntegerField(unique=True)),
                ("district", models.CharField(max_length=50)),
                ("cep", models.CharField(max_length=8)),
            ],
        ),
    ]
