# Generated by Django 4.1.5 on 2023-01-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="hospital",
        ),
    ]
