# Generated by Django 4.1.5 on 2023-01-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_remove_address_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="cep",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.IntegerField(),
        ),
    ]
