# Generated by Django 4.1.5 on 2023-01-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("Secretário", "Secretário"),
                    ("Médico", "Médico"),
                    ("Diretor", "Diretor"),
                ],
                max_length=20,
            ),
        ),
    ]
