# Generated by Django 4.1.5 on 2023-01-12 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_remove_address_hospital"),
        ("hospital", "0002_hospital_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital",
                to="address.address",
            ),
        ),
    ]
