# Generated by Django 4.1.5 on 2023-01-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_hospital_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="financial_goal",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="type_of_assistance",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="type_of_hospital",
        ),
    ]
